ALTER TABLE question
ADD COLUMN IF NOT EXISTS match_score DOUBLE PRECISION;

ALTER TABLE question
ADD COLUMN IF NOT EXISTS event_domain VARCHAR(100);

ALTER TABLE question
ADD COLUMN IF NOT EXISTS event_type VARCHAR(100);

ALTER TABLE question
ADD COLUMN IF NOT EXISTS background TEXT;
