ALTER TABLE question
ADD COLUMN IF NOT EXISTS area VARCHAR(200);

ALTER TABLE question
ADD COLUMN IF NOT EXISTS input_type VARCHAR(50);

ALTER TABLE question
ADD COLUMN IF NOT EXISTS delete_reason TEXT;
